### ISSUE TITLE
Implement the drain / secondary drain

### ISSUE THREAD

**Issue by vincent-herlemont** [vincent-herlemont/native_db#247]
`drain()` is a method that allows removing elements while returning them via an iterator.

It needs to be implemented for `primary` and `secondary`, with scan queries such as `all`, `range`, and `start_with`. Inspiration can be taken from the scan implementation in [src/transaction/query/scan/mod.rs](https://github.com/vincent-herlemont/native_db/blob/f3523f9ae2c2158ff918e6bdc71173726fd8f06d/src/transaction/query/scan/mod.rs).

NOTE: There is already an implementation for `primary`, but it should be looked at to see if improvements can be made.
- [src/transaction/query/drain.rs#L9-L20](https://github.com/vincent-herlemont/native_db/blob/b5a0d4c39c6f803c8acb499777e3dba28e010993/src/transaction/query/drain.rs#L9-L20)
- [possible improvements ...](https://github.com/vincent-herlemont/native_db/blob/7810f2f2059d536b5a3d50bb61052df49ff684de/src/transaction/internal/rw_transaction.rs#L215)

# TODO

- [ ] Improve [primary drain](https://github.com/vincent-herlemont/native_db/blob/b5a0d4c39c6f803c8acb499777e3dba28e010993/src/transaction/query/drain.rs#L9-L20)
    - [ ] Implement primary drain `all`
    - [ ] Implement primary drain `range`
    - [ ] Implement primary drain `start_with`
- [ ] Implement secondary drain.
    - [ ] Implement secondary drain `all`
    - [ ] Implement secondary drain `range`
    - [ ] Implement secondary drain `start_with`
