### ISSUE TITLE
Add cargo fmt and cargo clippy in the CI

### ISSUE THREAD

**Issue by vincent-herlemont** [vincent-herlemont/native_db#258]
Currently, even if the project is well formatted, `cargo fmt` and `cargo clippy` are not configured in the CI. We also need to make the last fixes for cargo clippy that have not been done.

# TODO
- [ ] Make the last fixes for cargo clippy
- [ ] Add a job for `cargo fmt`
- [ ] Add a job for `cargo clippy`
